---
services:
  backend:
    container_name: shop-ramsy-dev-backend
    build: ./backend
    volumes:
      - '/app/node_modules'
      - ./backend:/app
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    restart: always
  frontend:
    container_name: shop-ramsy-dev-frontend
    build: ./frontend
    volumes:
      - '/app/node_modules'
      - ./frontend:/app
    ports:
      - 7777:7777
    env_file:
      - ./frontend/.env
    restart: always
